export const SAMPLE = 'SAMPLE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_TRANSACTION_OVERVIEW = 'SET_TRANSACTION_OVERVIEW';
export const SET_IS_FILTER_ENABLED = 'SET_IS_FILTER_ENABLED';
export const SET_TRANSACTION_DATA = 'SET_TRANSACTION_DATA';
export const SET_CURRENT_FILTER_MONTH = 'SET_CURRENT_FILTER_MONTH';
export const SET_CURRENT_FILTER_GROUP_BY = 'SET_CURRENT_FILTER_GROUP_BY';
