export const SAMPLE = 'SAMPLE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_TRANSACTION_OVERVIEW = 'SET_TRANSACTION_OVERVIEW';
export const SET_IS_FILTER_ENABLED = 'SET_IS_FILTER_ENABLED';
export const SET_TRANSACTION_DETAILS = 'SET_TRANSACTION_DETAILS';
